sudo: required
services:
  - docker
languages: node_js
before_install:
  - docker build -t maheshs -f Dockerfile .
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  on:
    branch: release